spring:
  datasource:
    url: jdbc:mysql://192.168.99.101:32769/confitura-next
    username: root
    password: root
    max-active: 20
    max-idle: 8
    min-idle: 5
    initial-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
      active: fake

logging:
  level.: DEBUG

#spring.groovy.template.check-template-location=false



mandril:
  key: fake
gui:
  host: http://localhost:9090