spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:33061/confitura
    username: root
    password: root
    max-active: 20
    max-idle: 8
    min-idle: 5
    initial-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

  profiles:
      active: fake

logging:
  level.: INFO
#spring.
#spring.groovy.template.check-template-location=false


server:
  port: 9090
mandril:
  key: fake
gui:
  host: http://localhost:8080